config/routes.rb
Tremello::Application.routes.draw do

  root :to => 'sessions#create'
  
  resources :bands
  resources :musicians
  resources :locations
  resources :invitations

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'musicians#new'

end

app/models/musician.rb
class Musician < ActiveRecord::Base
	has_secure_password
  validates :password, :presence => { :on => :create }

  attr_accessible :bio, :email, :name, :bands_attributes, :password, :password_confirmation, :location_id

  has_many :memberships
  has_many :bands, :through => :memberships

  belongs_to :location 

  accepts_nested_attributes_for :bands

  validates_uniqueness_of :email
  
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  skip_before_filter :login_required, :only => ["new", "create"]
  # GET /musicians
  # GET /musicians.json
  def index
    @musicians = Musician.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @musicians }
    end
  end

  # GET /musicians/1
  # GET /musicians/1.json
  def show
    @musician = Musician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @musician }
    end
  end

  # GET /musicians/new
  # GET /musicians/new.json
  def new
    @musician = Musician.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @musician }
    end
  end

  # GET /musicians/1/edit
  def edit
    @musician = Musician.find(params[:id])
  end

  # POST /musicians
  # POST /musicians.json
  def create
    @musician = Musician.new(params[:musician])

    respond_to do |format|
      if @musician.save
        login(@musician)
        format.html { redirect_to @musician, notice: 'Welcome to Tremello!' }
        format.json { render json: @musician, status: :created, location: @musician }
      else
        format.html { render action: "new" }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /musicians/1
  # PUT /musicians/1.json
  def update
    @musician = Musician.find(params[:id])

    respond_to do |format|
      if @musician.update_attributes(params[:musician])
        format.html { redirect_to @musician, notice: 'Musician was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicians/1
  # DELETE /musicians/1.json
  def destroy
    @musician = Musician.find(params[:id])
    @musician.destroy

    respond_to do |format|
      format.html { redirect_to musicians_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/musicians_helper.rb
module MusiciansHelper
  def inviteable_musicians(musician)
    Musician.all.collect {|m| [ m.name, m.id ] }.reject{|m| m == [musician.name, musician.id]}
  end

  def inviteable_bands(musician)
    musician.bands.collect {|b| [ b.name, b.id ] }
  end

end

app/views/musicians/_form.html.erb
<%= form_for(@musician) do |f| %>
  <% if @musician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@musician.errors.count, "error") %> prohibited this musician from being saved:</h2>

      <ul>
      <% @musician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_field :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musicians/edit.html.erb
<h1>Editing musician</h1>

<%= render 'form' %>

<%= link_to 'Show', @musician %> |
<%= link_to 'Back', musicians_path %>

app/views/musicians/index.html.erb
<h1>Listing musicians</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Bio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @musicians.each do |musician| %>
  <tr>
    <td><%= musician.name %></td>
    <td><%= musician.email %></td>
    <td><%= musician.bio %></td>
    <td><%= link_to 'Show', musician %></td>
    <td><%= link_to 'Edit', edit_musician_path(musician) %></td>
    <td><%= link_to 'Destroy', musician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Musician', new_musician_path %>

app/views/musicians/new.html.erb
<h1>New musician</h1>

<%= render 'form' %>

<%= link_to 'Back', musicians_path %>

app/views/musicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @musician.name %>
</p>

<p>
  <b>Email:</b>
  <%= @musician.email %>
</p>

<p>
  <b>Bio:</b>
  <%= @musician.bio %>
</p>

<p>
  <% if @musician.location_id? %>
    <b>Where I jam:</b>
    <%= @musician.location.full_address %> 
    <br>
    <%= link_to 'I jam elsewhere now', edit_location_path(@musician.location_id) %> |
    <%= link_to "I'm currently homeless", 
    location_path(@musician.location_id),  method: :delete %>
  <% else %>
    <b>Add a location:</b>
    <%= link_to 'Where I jam', new_location_path %>
  <% end %>
</p>

<p>
  <b>Bands I belong to:</b>
  <ul>
    <% @musician.bands.each do |band| %>
      <li><%= link_to band.name, band %></li>
    <% end %>
    <li><%= link_to 'Add New Band', new_band_path %></li>
  </ul>
</p>

<%= link_to 'Edit', edit_musician_path(@musician) %> |
<%= link_to 'Back', musicians_path %>