config/routes.rb
Tremello::Application.routes.draw do

  root :to => 'sessions#create'
  
  resources :bands
  resources :musicians
  resources :locations
  resources :invitations

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'musicians#new'

end

app/models/invitation.rb
 class Invitation < ActiveRecord::Base
  attr_accessible :status, :inviter_id, :invitee_id, :band_id

  STATUS = {
    :sent => 0,
    :accepted => 1,
    :declined => 2
  }

  def accept
    self.status = STATUS[:accepted]
    self.save
    member_accepted = Membership.where(:band_id => self.band.id, :musician_id => self.invitee.id).first_or_create
  end

  def inviter
    Musician.find_by_id(self.inviter_id)
  end

  def invitee
    Musician.find_by_id(self.invitee_id)
  end

  def band
    Band.find_by_id(self.band_id)
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
    @invitation = Invitation.find(params[:id])
    @inviter = @invitation.inviter
    @invitee = @invitation.invitee
    @band = @invitation.band
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/new
  # GET /invitations/new.json
  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/1/edit
  def edit
    @invitation = Invitation.find(params[:id])
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(params[:invitation])
    @invitation.inviter_id = @current_user.id
    @invitation.status = Invitation::STATUS[:sent]
    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
        format.json { render json: @invitation, status: :created, location: @invitation }
      else
        format.html { render action: "new" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.json
  def update
    @invitation = Invitation.find(params[:id])
    # @invitation.inviter_id = @current_user.id
    @invitation.accept if params[:invitation][:status].to_i == Invitation::STATUS[:accepted]
    
    respond_to do |format|
      if @invitation.update_attributes(params[:invitation])
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_page?(new_invitation_path) %>
    <%= render :partial => 'form_fields', :locals => { :f => f } %>
  <% end %>
  
  <% unless current_page?(new_invitation_path) %>
    <%= render :partial => 'form_actions', :locals => { :f => f } %>
  <% end %>

  <%= render :partial => 'form_submit', :locals => { :f => f } %>

<% end %>

app/views/invitations/_form_actions.html.erb
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, options_for_select(Invitation::STATUS) %>
  </div>

app/views/invitations/_form_fields.html.erb
  <div class="field">
    <label for="invitation_invitee_id">Who do you want to invite?</label><br />
    <%= f.select :invitee_id, options_for_select(inviteable_musicians(@current_user)) %>
  </div>
  <div class="field">
    <%= f.label :band_id %><br />
    <%= f.select :band_id, options_for_select(inviteable_bands(@current_user)) %>
  </div>

app/views/invitations/_form_submit.html.erb
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Inviter</th>
    <th>Invitee</th>
    <th>Band</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.status %></td>
    <td><%= invitation.inviter.name %></td>
    <td><%= invitation.invitee.name %></td>
    <td><%= invitation.band.name %></td>
    <td><%= link_to 'Show', invitation %></td>
    <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
    <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @invitation.status %>
</p>

<p>
  <b>Inviter:</b>
  <%= @inviter.name %>
</p>

<p>
  <b>Invitee:</b>
  <%= @invitee.name %>
</p>

<p>
  <b>Band:</b>
  <%= @band.name %>
</p>


<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>